# Generated by Django 2.0.5 on 2019-02-21 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_in_url', models.SlugField(max_length=100, unique_for_date='publish')),
                ('title', models.CharField(max_length=100)),
                ('article_content', models.TextField()),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('D', 'Drafted'), ('P', 'Published')], max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish_time',),
            },
        ),
    ]
