# Generated by Django 2.0.5 on 2019-03-06 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('comment_content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='article',
            name='label_in_url',
            field=models.SlugField(max_length=100, unique_for_date='publish_time'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('id', 'author')},
        ),
        migrations.AlterModelTable(
            name='article',
            table='article_from_user',
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='article.Article'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
        migrations.RemoveField(
            model_name='article',
            name='update_time',
        ),
    ]
