# Generated by Django 2.0.5 on 2019-03-07 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190306_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_time',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
