# Generated by Django 2.0.5 on 2019-03-07 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190307_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
