# Generated by Django 2.0.5 on 2019-03-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_total_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
    ]
